name: Accept PRs into alpha
on:
  pull_request:
    branches:
      - alpha
    types: [opened, synchronize, reopened]

jobs:
    merge_and_push:
        runs-on: ubuntu-latest
        env:
          WST_ADMIN_USERNAME: admin
          WST_ADMIN_PWD: testadmin
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
              ref: alpha

        - name: Merge PR
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git merge --no-edit --no-ff ${{ github.event.pull_request.branch.name }}

        - name: Create go tag with date
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

        - name: Fetch all tags
          run: git fetch --prune --unshallow --tags

        - name: Find latest tag with regex v\d+\.\d+\.\d+$ and fallback to 0.0.0
          id: latest_tag
          run: |
            latest_tag=$(git describe --tags --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0)
            major=$(echo $latest_tag | cut -d. -f1)
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)
            patch=${patch%-*}
            patch=${patch%-*}
            patch=$((patch + 1))
            latest_tag=${major}.${minor}.${patch}
            echo "::set-output name=tag::${major}.${minor}.${patch}"
            echo "Found latest tag: $latest_tag"

        - name: Install MongoDB
          run: |
            sudo apt-get update
            sudo apt-get install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
            wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.19

        - name: Start MongoDB
          run: sudo systemctl start mongod

        - name: Test WeStack
          run: go test -v ./westack/tests

        - name: Create tag
          run: git tag -a v${{ steps.latest_tag.outputs.tag }}-alpha-${{ steps.date.outputs.date }} -m "v${{ steps.latest_tag.outputs.tag }}-${{ steps.date.outputs.date }}"

        - name: Push
          uses: ad-m/github-push-action@master
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: alpha

        - name: Close the pull request
          run: |
            curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"state": "closed"}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
