name: Accept PRs into alpha
on:
  pull_request:
    branches:
      - alpha
    types: [opened, synchronize, reopened]

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
        - name: Merge PR
          uses: actions/github-script@v5
          with:
              github-token: ${{ secrets.PULL_REQUEST_TOKEN }}
              script: |
                  github.pulls.merge({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: context.payload.pull_request.number
                  })
