name: Accept PRs into alpha
on:
  pull_request:
    branches:
      - alpha
      - update-dependencies
      - master
    types: [opened, synchronize, reopened]

jobs:
    merge_and_push:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go: [ '1.19', '1.20.1', '1.20.6' ]
        env:
          WST_ADMIN_USERNAME: admin
          WST_ADMIN_PWD: testadmin
          PPROF_AUTH_USERNAME: test
          PPROF_AUTH_PASSWORD: abcd1234.
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
        steps:
        - name: Checkout master
          uses: actions/checkout@v2
          with:
              ref: master

        - name: Create go tag with date
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

        - name: Fetch all tags
          run: git fetch --prune --unshallow --tags

        - name: Find latest tag with regex v\d+\.\d+\.\d+$ and fallback to 0.0.0, skipping -alpha and -beta
          id: latest_tag
          run: |
            latest_tag=$(git describe --tags --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 | grep -v -E "alpha|beta" || echo "v0.0.0")
            major=$(echo $latest_tag | cut -d. -f1)
            major=${major#v}
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)
            patch=${patch%-*}
            patch=${patch%-*}
            latest_tag=${major}.${minor}.${patch}
            echo "Found latest tag: $latest_tag"
            major=$((major + 1))
            minor="0"
            patch="0"
            new_tag=${major}.${minor}.${patch}
            echo "Tagging new as: $new_tag"
            echo "::set-output name=tag::${new_tag}"

        - name: Checkout alpha
          run: |
            git checkout -b alpha origin/alpha
            git pull

        - name: Merge PR
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git merge --no-edit --no-ff --allow-unrelated-histories ${{ github.event.pull_request.head.sha }}

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: ${{ matrix.go }}
            check-latest: true
            cache-dependency-path: ${{ github.workspace }}/go.sum

        - name: Setup Gosec Security Scanner
          timeout-minutes: 15
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            go install github.com/securego/gosec/v2/cmd/gosec@latest

        - name: Install jq
          run: |
            sudo apt-get install -y jq

        - name: Run Gosec Security Scanner
          run: |
            golangci-lint run --timeout 10m --disable-all --enable=gosec --out-format=json ./... > results.json 2>&1 || true
            result=0
            # Parse results.json
            if [ -f results.json ]; then
              result=$(cat results.json | jq '.Issues | length')
            fi
            if [ $result -ne 0 ]; then
              echo "Gosec found issues"
              # Set output variable
                echo "::set-output name=issues_found::true"
            else
                echo "Gosec found no issues"
                # Set output variable
                echo "::set-output name=issues_found::false"
            fi
            exit 0

        - name: Upload results.json
          uses: actions/upload-artifact@v2
          with:
              name: results.json
              path: results.json

        - name: Exit if Gosec found issues
          if: steps.gosec.outputs.issues_found == 'true'
          run: exit 1

        - name: Install MongoDB
          run: |
            sudo apt-get update
            sudo apt-get install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
            wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org

        - name: Start MongoDB
          run: sudo systemctl start mongod

        - name: Test WeStack
          run: go test -v ./westack/tests -timeout 30m -coverprofile=coverage.txt -covermode=atomic -count=1

        - name: Upload coverage.txt
          uses: actions/upload-artifact@v2
          with:
              name: coverage.txt
              path: coverage.txt

#        - name: Create tag
#          run: git tag -a v${{ steps.latest_tag.outputs.tag }}-alpha-${{ steps.date.outputs.date }} -m "v${{ steps.latest_tag.outputs.tag }}-alpha-${{ steps.date.outputs.date }}"

        - name: Create a new branch
          run: |
            git checkout -b v-${{ steps.latest_tag.outputs.tag }}-alpha HEAD

        - name: Push
          run: |
            git push origin alpha
            git push -u origin v-${{ steps.latest_tag.outputs.tag }}-alpha
#            git push --tags

        - name: Comments on the pull request and closes it
          run: |
            curl -X POST -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"body": "This PR has been merged into alpha and tagged as ${{ steps.latest_tag.outputs.tag }}-alpha-${{ steps.date.outputs.date }}. Thanks for your contribution!"}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
            curl -X PATCH -H "Authorization: token ${{ secrets.PULL_REQUEST_TOKEN }}" -H "Content-Type: application/json" -d '{"state": "closed"}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
