name: Accept PRs into alpha
on:
  pull_request:
    branches:
      - alpha
    types: [opened, synchronize, reopened]

jobs:
    merge:
        runs-on: github-hosted
        steps:
        - name: Merge PR
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git fetch origin alpha
            git checkout alpha
            git merge --no-ff --no-edit ${{ github.event.pull_request.head.sha }}
            git push origin alpha
