name: Accept PRs into alpha
on:
  pull_request:
    branches:
      - alpha
    types: [opened, synchronize, reopened]

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
        - name: Merge PR
          uses: git
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git fetch
            git checkout alpha
            git merge --squash ${{ github.event.pull_request.head.sha }}
            git commit -m "Merge PR #${{ github.event.pull_request.number }} into alpha"
            git push
