name: Update Dependencies
on:
  schedule:
      - cron: '0 0/6 * * *'
  push:
    branches:
      - update-dependencies
  pull_request:
    branches:
      - update-dependencies
jobs:

  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout update-dependencies
        run: |
          git fetch
          git checkout -b update-dependencies origin/update-dependencies
          git pull

      - name: Merge PR
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git merge --no-edit --allow-unrelated-histories ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Install Go Dependencies
        run: |
          go get -u ./...
          go mod tidy
          go mod verify
          go mod download

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update dependencies"
          git push origin update-dependencies